# Copyright (C) 2019-2025 GEM Foundation
#
# OpenQuake is free software: you can redistribute it and/or modify it
# under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# OpenQuake is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with OpenQuake. If not, see <http://www.gnu.org/licenses/>.
FROM python:3.11.6-slim AS compile-image
LABEL maintainer="GEM Foundation <devops@openquake.org>" \
    vendor="GEM Foundation"
RUN useradd -m -u 1000 -s /bin/bash openquake
RUN apt-get update &&  apt-get install -y --no-install-recommends build-essential gcc libcap-dev
# Create venv
ENV VIRTUAL_ENV=/opt/openquake
RUN python3 -m venv $VIRTUAL_ENV
ENV PATH="$VIRTUAL_ENV/bin:$PATH"
# Copy local code and install engine
COPY --chown=openquake:openquake . /tmp/oq-engine
RUN cd /tmp/oq-engine && \
    pip --disable-pip-version-check install . -r requirements-py311-linux64.txt --no-warn-script-location && \
    rm -rf /tmp/oq-engine && \
    DEST_DIR=/opt/openquake/lib/python3.11/site-packages/openquake/server/templates/registration && \
    cp ${DEST_DIR}/password_reset_email_content.txt.default.tmpl ${DEST_DIR}/password_reset_email_content.txt && \
    cp ${DEST_DIR}/password_reset_email_subject.txt.default.tmpl ${DEST_DIR}/password_reset_email_subject.txt && \
    cp ${DEST_DIR}/normal_user_creation_email_content.txt.default.tmpl ${DEST_DIR}/normal_user_creation_email_content.txt && \
    cp ${DEST_DIR}/normal_user_creation_email_subject.txt.default.tmpl ${DEST_DIR}/normal_user_creation_email_subject.txt
#
FROM python:3.11.6-slim AS build-image
COPY --from=compile-image /opt/openquake/ /opt/openquake/
ENV LANG=en_US.UTF-8
ENV LOCKDOWN=False
RUN useradd -m -u 1000 -s /bin/bash openquake
USER openquake
ENV HOME=/home/openquake
WORKDIR ${HOME}
ENV PATH="/opt/openquake/bin:$PATH"
#
ADD docker/scripts/oq-start.sh ${HOME}
RUN mkdir oqdata
EXPOSE 8800
STOPSIGNAL SIGINT
ENTRYPOINT ["/bin/bash", "-c"]
CMD ["./oq-start.sh"]  
